# -*- coding: utf-8 -*-
"""Rozszerzone teksty SEO i FAQ dla stron usług.

Trzymane osobno od i18n.py, bo to dluzsze akapity, a nie etykiety interfejsu.
Struktura:  SEO[slug] = {"h": {..}, "text": [{..}, ..], "faq": [{"q":{..},"a":{..}}, ..]}
Kazdy slownik ma klucze pl/uk/ru/en.
"""

SEO = {}

SEO["manicure"] = {
 "h": {"pl":"Manicure w Szczecinie — co warto wiedzieć",
       "uk":"Манікюр у Щеціні — що варто знати",
       "ru":"Маникюр в Щецине — что стоит знать",
       "en":"Manicure in Szczecin — what to know"},
 "text": [
  {"pl":"Do salonu przy alei Wyzwolenia 5/10 przychodzą klientki z całego Szczecina — z Centrum, Śródmieścia, Turzyna i Niebuszewa. Każdą wizytę zaczynamy od oceny stanu płytki i skórek, bo od tego zależy, czy hybryda utrzyma się trzy tygodnie, czy odpryśnie po kilku dniach. Pracujemy metodą kombinowaną: frez do opracowania wału, nożyczki tam, gdzie trzeba precyzji.",
   "uk":"До салону на алеї Wyzwolenia 5/10 приходять клієнтки з усього Щеціна — з центру, Śródmieście, Turzyn і Niebuszewo. Кожен візит починаємо з оцінки стану нігтьової пластини та кутикули, бо саме від цього залежить, чи протримається гібрид три тижні. Працюємо комбінованою технікою: фреза для обробки валика, ножиці там, де потрібна точність.",
   "ru":"В салон на аллее Wyzwolenia 5/10 приходят клиентки со всего Щецина — из центра, Śródmieście, Turzyn и Niebuszewo. Каждый визит начинаем с оценки состояния пластины и кутикулы, потому что именно от этого зависит, продержится ли гибрид три недели. Работаем комбинированной техникой: фреза для обработки валика, ножницы там, где нужна точность.",
   "en":"Clients come to our salon at aleja Wyzwolenia 5/10 from across Szczecin — the city centre, Śródmieście, Turzyn and Niebuszewo. Every appointment starts with an assessment of the nail plate and cuticles, because that decides whether the gel polish lasts three weeks or chips after a few days. We work with a combined technique: an e-file for the nail fold, scissors wherever precision matters."},
  {"pl":"W cenniku znajdziesz manicure higieniczny, hybrydowy, japoński, męski i metodą suchą, a także paznokcie żelowe oraz przedłużanie na dual formach w kilku długościach. Doradzamy długość i kształt pod kształt dłoni i tryb pracy — krótkie migdały sprawdzą się przy pracy z klawiaturą, dłuższe kwadraty przy okazjach. Kolor dobieramy na miejscu, wzornik mamy pełny.",
   "uk":"У прайсі є гігієнічний, гібридний, японський, чоловічий манікюр і манікюр сухою технікою, а також гелеві нігті та нарощування на дуальних формах кількох довжин. Радимо довжину й форму під форму руки та спосіб життя: короткий мигдаль зручний для роботи за клавіатурою, довший квадрат — для особливих подій. Колір добираємо на місці, палітра повна.",
   "ru":"В прайсе есть гигиенический, гибридный, японский, мужской маникюр и маникюр сухой техникой, а также гелевые ногти и наращивание на дуальных формах нескольких длин. Советуем длину и форму под форму руки и образ жизни: короткий миндаль удобен при работе за клавиатурой, длинный квадрат — для особых случаев. Цвет подбираем на месте, палитра полная.",
   "en":"The price list covers hygienic, hybrid, Japanese, men's and dry-technique manicure, plus gel nails and dual-form extensions in several lengths. We advise on length and shape based on your hand and your daily routine: short almonds work well if you type all day, longer squares suit special occasions. Colour is chosen on the spot from a full swatch set."},
  {"pl":"Na wizytę umawiasz się online przez Booksy, o dowolnej porze. Pierwsze przyjście warto zaplanować z zapasem — przy zaniedbanej płytce lub uzupełnianiu pracy z innego salonu zabieg trwa dłużej. Jeśli nie wiesz, którą usługę wybrać, napisz do nas: dobierzemy pozycję z cennika i realny czas wizyty.",
   "uk":"Записатися можна онлайн через Booksy у будь-який час. Перший візит краще планувати із запасом: якщо пластина занедбана або ви приходите на корекцію роботи з іншого салону, процедура триває довше. Не знаєте, яку послугу обрати — напишіть нам, підберемо позицію з прайсу та реальний час візиту.",
   "ru":"Записаться можно онлайн через Booksy в любое время. Первый визит лучше планировать с запасом: если пластина запущена или вы приходите на коррекцию работы из другого салона, процедура длится дольше. Не знаете, какую услугу выбрать — напишите нам, подберём позицию из прайса и реальное время визита.",
   "en":"You can book online through Booksy at any hour. Allow extra time for a first visit: if the nail plate needs repair, or you are having work from another salon filled in, the appointment runs longer. If you are unsure which service to pick, message us and we will match it to the price list and to a realistic appointment length."},
 ],
 "faq": [
  {"q":{"pl":"Ile kosztuje manicure hybrydowy w Szczecinie?",
        "uk":"Скільки коштує гібридний манікюр у Щеціні?",
        "ru":"Сколько стоит гибридный маникюр в Щецине?",
        "en":"How much does a gel manicure cost in Szczecin?"},
   "a":{"pl":"W BAD ANGEL manicure hybrydowy kosztuje {cena:Manicure hybrydowy}, higieniczny {cena:Manicure higieniczny}, a japoński {cena:Manicure japoński}. Pełne, aktualne stawki znajdziesz w cenniku na tej stronie — są te same co w Booksy.",
        "uk":"У BAD ANGEL гібридний манікюр коштує {cena:Manicure hybrydowy}, гігієнічний — {cena:Manicure higieniczny}, японський — {cena:Manicure japoński}. Повний актуальний прайс є на цій сторінці, ціни ті самі, що в Booksy.",
        "ru":"В BAD ANGEL гибридный маникюр стоит {cena:Manicure hybrydowy}, гигиенический — {cena:Manicure higieniczny}, японский — {cena:Manicure japoński}. Полный актуальный прайс есть на этой странице, цены те же, что в Booksy.",
        "en":"At BAD ANGEL a gel manicure is {cena:Manicure hybrydowy}, a hygienic one {cena:Manicure higieniczny} and a Japanese one {cena:Manicure japoński}. The complete current pricing is on this page and matches Booksy."}},
  {"q":{"pl":"Jak długo trzyma się manicure hybrydowy?",
        "uk":"Скільки тримається гібридний манікюр?",
        "ru":"Сколько держится гибридный маникюр?",
        "en":"How long does a gel manicure last?"},
   "a":{"pl":"Zwykle od trzech do czterech tygodni. Krócej, jeśli paznokcie szybko rosną albo dużo pracujesz rękami w wodzie i detergentach. Na kolejną wizytę najlepiej umówić się, zanim odrost stanie się widoczny — praca jest wtedy szybsza i tańsza niż pełna rekonstrukcja.",
        "uk":"Зазвичай три-чотири тижні. Менше, якщо нігті швидко ростуть або ви багато працюєте руками у воді й з побутовою хімією. На наступний візит краще записатися до того, як відросток стане помітним: робота тоді швидша й дешевша за повну реконструкцію.",
        "ru":"Обычно три-четыре недели. Меньше, если ногти быстро растут или вы много работаете руками в воде и с бытовой химией. На следующий визит лучше записаться до того, как отросток станет заметным: работа тогда быстрее и дешевле полной реконструкции.",
        "en":"Usually three to four weeks. Less if your nails grow quickly or you often work with water and detergents. Book the next appointment before the regrowth becomes obvious — the work is then faster and cheaper than a full rebuild."}},
  {"q":{"pl":"Czy robicie manicure na krótkich, obgryzionych paznokciach?",
        "uk":"Чи робите манікюр на коротких, обгризених нігтях?",
        "ru":"Делаете ли маникюр на коротких, обгрызенных ногтях?",
        "en":"Do you work on short, bitten nails?"},
   "a":{"pl":"Tak. Przy bardzo krótkiej płytce zaczynamy od żelu na naturalny paznokieć albo od przedłużenia na dual formach, żeby odbudować kształt. Po dwóch, trzech uzupełnieniach płytka zwykle wraca do normalnej długości.",
        "uk":"Так. За дуже короткої пластини починаємо з гелю на натуральний ніготь або з нарощування на дуальних формах, щоб відновити форму. Після двох-трьох корекцій пластина зазвичай повертається до нормальної довжини.",
        "ru":"Да. При очень короткой пластине начинаем с геля на натуральный ноготь или с наращивания на дуальных формах, чтобы восстановить форму. После двух-трёх коррекций пластина обычно возвращается к нормальной длине.",
        "en":"Yes. With a very short nail plate we start with gel on the natural nail or dual-form extensions to rebuild the shape. After two or three fills the nail is usually back to a normal length."}},
  {"q":{"pl":"Czy trzeba się umawiać wcześniej?",
        "uk":"Чи потрібен попередній запис?",
        "ru":"Нужна ли предварительная запись?",
        "en":"Do I need to book in advance?"},
   "a":{"pl":"Tak, pracujemy wyłącznie na umówione wizyty. Terminy na manicure schodzą zwykle z kilkudniowym wyprzedzeniem, przed weekendem i świętami szybciej.",
        "uk":"Так, працюємо лише за попереднім записом. Місця на манікюр зазвичай розбирають за кілька днів, перед вихідними та святами — швидше.",
        "ru":"Да, работаем только по предварительной записи. Места на маникюр обычно разбирают за несколько дней, перед выходными и праздниками — быстрее.",
        "en":"Yes, we work by appointment only. Manicure slots usually go a few days ahead, and faster before weekends and holidays."}},
  {"q":{"pl":"Gdzie znajduje się salon i jak dojechać?",
        "uk":"Де розташований салон і як дістатися?",
        "ru":"Где находится салон и как добраться?",
        "en":"Where is the salon and how do I get there?"},
   "a":{"pl":"aleja Wyzwolenia 5/10 w Szczecinie, wejście od ulicy Małopolskiej — to ścisłe centrum, kilka minut od placu Rodła i przystanków tramwajowych. Na miejscu jest parking i Wi-Fi.",
        "uk":"aleja Wyzwolenia 5/10 у Щеціні, вхід з вулиці Małopolska — це самий центр, кілька хвилин від площі Rodła та трамвайних зупинок. На місці є паркінг і Wi-Fi.",
        "ru":"aleja Wyzwolenia 5/10 в Щецине, вход с улицы Małopolska — это самый центр, несколько минут от площади Rodła и трамвайных остановок. На месте есть парковка и Wi-Fi.",
        "en":"aleja Wyzwolenia 5/10 in Szczecin, entrance from Małopolska street — the very centre, a few minutes from plac Rodła and the tram stops. Parking and Wi-Fi on site."}},
 ],
}

SEO["pedicure"] = {
 "h": {"pl":"Pedicure w Szczecinie — jak pracujemy",
       "uk":"Педикюр у Щеціні — як ми працюємо",
       "ru":"Педикюр в Щецине — как мы работаем",
       "en":"Pedicure in Szczecin — how we work"},
 "text": [
  {"pl":"Pedicure robimy w osobnym, zamkniętym stanowisku — to nie jest zabieg, przy którym chce się siedzieć na widoku. Zaczynamy od kąpieli i zmiękczenia, potem opracowanie paznokci, wałów i pięt. Zrogowaciały naskórek i pęknięte pięty schodzą frezem, bez brutalnego skrobania.",
   "uk":"Педикюр робимо в окремому закритому місці — це не та процедура, під час якої хочеться сидіти на видноті. Починаємо з ванночки та розм'якшення, далі обробка нігтів, валиків і п'ят. Ороговілу шкіру та тріщини знімаємо фрезою, без грубого зішкрібання.",
   "ru":"Педикюр делаем в отдельном закрытом месте — это не та процедура, во время которой хочется сидеть на виду. Начинаем с ванночки и размягчения, дальше обработка ногтей, валиков и пяток. Ороговевшую кожу и трещины снимаем фрезой, без грубого соскабливания.",
   "en":"We do pedicures in a separate, screened-off station — it is not a treatment you want to have in full view. We start with a soak, then work the nails, the nail folds and the heels. Calluses and cracked heels are taken down with an e-file, without harsh scraping."},
  {"pl":"Do wyboru jest pedicure higieniczny, męski, ze zwykłym lakierem oraz hybrydowy — w wersji z pełnym opracowaniem stopy albo samych paznokci. Wersja ze stopą trwa dłużej, ale jest tym, po co przychodzi większość osób latem, przed sezonem sandałów i urlopem.",
   "uk":"На вибір: гігієнічний, чоловічий педикюр, зі звичайним лаком і гібридний — у варіанті з повною обробкою стопи або лише нігтів. Варіант зі стопою триває довше, але саме по нього приходить більшість влітку, перед сезоном босоніжок і відпусткою.",
   "ru":"На выбор: гигиенический, мужской педикюр, с обычным лаком и гибридный — в варианте с полной обработкой стопы или только ногтей. Вариант со стопой длится дольше, но именно за ним приходит большинство летом, перед сезоном босоножек и отпуском.",
   "en":"You can choose hygienic, men's, regular-polish or gel pedicure, either with full foot work or nails only. The full-foot version takes longer, but it is what most people come for in summer, before sandal season and holidays."},
  {"pl":"Wrastające paznokcie, modzele i odciski oglądamy na wizycie i mówimy wprost, czy da się to opracować kosmetycznie, czy lepiej najpierw do podologa. Nie obiecujemy efektów, których zabieg kosmetyczny nie daje.",
   "uk":"Врослі нігті, мозолі та натоптиші оглядаємо на візиті й прямо кажемо, чи можна це опрацювати косметично, чи краще спершу до подолога. Не обіцяємо результатів, яких косметична процедура не дає.",
   "ru":"Вросшие ногти, мозоли и натоптыши осматриваем на визите и прямо говорим, можно ли это обработать косметически или лучше сначала к подологу. Не обещаем результатов, которых косметическая процедура не даёт.",
   "en":"We look at ingrown nails, corns and calluses during the visit and tell you plainly whether cosmetic work is enough or whether a podiatrist should see it first. We do not promise results a cosmetic treatment cannot deliver."},
 ],
 "faq": [
  {"q":{"pl":"Ile kosztuje pedicure hybrydowy w Szczecinie?",
        "uk":"Скільки коштує гібридний педикюр у Щеціні?",
        "ru":"Сколько стоит гибридный педикюр в Щецине?",
        "en":"How much does a gel pedicure cost in Szczecin?"},
   "a":{"pl":"Pedicure hybrydowy bez opracowania stopy kosztuje {cena:Pedicure hybrydowy (bez stopy)}, a z pełnym opracowaniem stopy {cena:Pedicure hybrydowy + stopy}. Pedicure higieniczny to {cena:Pedicure higieniczny}. Aktualne pozycje i czasy trwania są w cenniku wyżej na tej stronie.",
        "uk":"Гібридний педикюр без обробки стопи коштує {cena:Pedicure hybrydowy (bez stopy)}, з повною обробкою стопи — {cena:Pedicure hybrydowy + stopy}. Гігієнічний педикюр — {cena:Pedicure higieniczny}. Актуальні позиції та тривалість є у прайсі вище на цій сторінці.",
        "ru":"Гибридный педикюр без обработки стопы стоит {cena:Pedicure hybrydowy (bez stopy)}, с полной обработкой стопы — {cena:Pedicure hybrydowy + stopy}. Гигиенический педикюр — {cena:Pedicure higieniczny}. Актуальные позиции и длительность есть в прайсе выше на этой странице.",
        "en":"A gel pedicure without foot work is {cena:Pedicure hybrydowy (bez stopy)}, and with full foot work {cena:Pedicure hybrydowy + stopy}. A hygienic pedicure is {cena:Pedicure higieniczny}. Current items and durations are in the price list above."}},
  {"q":{"pl":"Jak często robić pedicure?",
        "uk":"Як часто робити педикюр?",
        "ru":"Как часто делать педикюр?",
        "en":"How often should I have a pedicure?"},
   "a":{"pl":"Latem zwykle co cztery, pięć tygodni, zimą rzadziej — co sześć, osiem. Paznokcie u stóp rosną wolniej niż u rąk, więc lakier hybrydowy wytrzymuje na nich dłużej niż na dłoniach.",
        "uk":"Влітку зазвичай кожні чотири-п'ять тижнів, узимку рідше — кожні шість-вісім. Нігті на ногах ростуть повільніше, ніж на руках, тож гібридне покриття тримається на них довше.",
        "ru":"Летом обычно каждые четыре-пять недель, зимой реже — каждые шесть-восемь. Ногти на ногах растут медленнее, чем на руках, поэтому гибридное покрытие держится на них дольше.",
        "en":"In summer usually every four to five weeks, in winter less often, every six to eight. Toenails grow more slowly than fingernails, so gel polish lasts longer on them."}},
  {"q":{"pl":"Czy robicie pedicure dla mężczyzn?",
        "uk":"Чи робите педикюр для чоловіків?",
        "ru":"Делаете ли педикюр для мужчин?",
        "en":"Do you do pedicures for men?"},
   "a":{"pl":"Tak, pedicure męski jest osobną pozycją w cenniku. To zabieg pielęgnacyjny bez koloru: opracowanie paznokci, wałów i zrogowaciałego naskórka.",
        "uk":"Так, чоловічий педикюр — окрема позиція у прайсі. Це доглядова процедура без кольору: обробка нігтів, валиків та ороговілої шкіри.",
        "ru":"Да, мужской педикюр — отдельная позиция в прайсе. Это уходовая процедура без цвета: обработка ногтей, валиков и ороговевшей кожи.",
        "en":"Yes, men's pedicure is a separate item on the price list. It is a care treatment without colour: nails, nail folds and calluses."}},
  {"q":{"pl":"Czy można zrobić manicure i pedicure podczas jednej wizyty?",
        "uk":"Чи можна зробити манікюр і педикюр за один візит?",
        "ru":"Можно ли сделать маникюр и педикюр за один визит?",
        "en":"Can I have a manicure and pedicure in one visit?"},
   "a":{"pl":"Tak, w cenniku jest wspólna pozycja manicure + pedicure. Warto zarezerwować taki termin z wyprzedzeniem, bo blokuje dłuższy blok czasu u jednej specjalistki.",
        "uk":"Так, у прайсі є спільна позиція манікюр + педикюр. Такий термін варто бронювати заздалегідь, бо він займає довший блок часу в однієї майстрині.",
        "ru":"Да, в прайсе есть общая позиция маникюр + педикюр. Такое время лучше бронировать заранее, потому что оно занимает длинный блок у одной мастерицы.",
        "en":"Yes, there is a combined manicure + pedicure item. Book it ahead of time, as it blocks a long slot with one specialist."}},
 ],
}

SEO["rzesy"] = {
 "h": {"pl":"Przedłużanie rzęs w Szczecinie — metody i trwałość",
       "uk":"Нарощування вій у Щеціні — методи та стійкість",
       "ru":"Наращивание ресниц в Щецине — методы и стойкость",
       "en":"Lash extensions in Szczecin — methods and wear"},
 "text": [
  {"pl":"Pracujemy w objętościach od 1:1 do 5:1. Metoda 1:1 to jedna sztuczna rzęsa na jedną własną — efekt, którego z odległości nie widać jako przedłużania. Im wyższa objętość, tym gęstsze i bardziej wyraziste spojrzenie; 4:1 i 5:1 wybierają zwykle osoby, które na co dzień nie malują oczu i chcą, żeby makijaż był już zrobiony.",
   "uk":"Працюємо в об'ємах від 1:1 до 5:1. Метод 1:1 — це одна штучна вія на одну свою: ефект, який здалеку не читається як нарощування. Що вищий об'єм, то густіший і виразніший погляд; 4:1 і 5:1 зазвичай обирають ті, хто щодня не фарбує очі й хоче, щоб макіяж уже був готовий.",
   "ru":"Работаем в объёмах от 1:1 до 5:1. Метод 1:1 — это одна искусственная ресница на одну свою: эффект, который издалека не читается как наращивание. Чем выше объём, тем гуще и выразительнее взгляд; 4:1 и 5:1 обычно выбирают те, кто не красит глаза каждый день и хочет, чтобы макияж был уже готов.",
   "en":"We work in volumes from 1:1 to 5:1. The 1:1 method is one extension per natural lash — an effect that does not read as extensions from a distance. The higher the volume, the denser and bolder the look; 4:1 and 5:1 are usually chosen by people who skip eye make-up and want it already done."},
  {"pl":"Długość i skręt dobieramy do kształtu oka i kondycji własnych rzęs. Nie zakładamy ciężkich objętości na cienką, osłabioną rzęsę, bo skutkiem jest wypadanie — wolimy powiedzieć to na konsultacji niż tłumaczyć po fakcie. Pierwsza aplikacja trwa około dwóch godzin i przez ten czas leży się z zamkniętymi oczami.",
   "uk":"Довжину й вигин добираємо під форму ока та стан власних вій. Не ставимо важкі об'єми на тонку ослаблену вію, бо наслідок — випадіння; краще сказати це на консультації, ніж пояснювати постфактум. Перша аплікація триває близько двох годин, і весь цей час ви лежите із заплющеними очима.",
   "ru":"Длину и изгиб подбираем под форму глаза и состояние собственных ресниц. Не ставим тяжёлые объёмы на тонкую ослабленную ресницу, потому что результат — выпадение; лучше сказать это на консультации, чем объяснять постфактум. Первая аппликация длится около двух часов, и всё это время вы лежите с закрытыми глазами.",
   "en":"Length and curl are matched to your eye shape and the condition of your own lashes. We do not put heavy volumes on thin, weakened lashes, because the result is shedding — we would rather say so at the consultation than explain it afterwards. A first application takes about two hours, lying down with your eyes closed."},
  {"pl":"Uzupełnienie robimy do trzech tygodni od aplikacji — później zostaje za mało własnych rzęs, żeby dołożyć, i wychodzi taniej zrobić komplet od nowa. Jeśli masz pracę z innego salonu, którą chcesz zdjąć, napisz o tym przy rezerwacji — wycenimy ściągnięcie indywidualnie.",
   "uk":"Корекцію робимо до трьох тижнів після аплікації — пізніше залишається замало власних вій, щоб додати, і дешевше зробити комплект заново. Якщо у вас робота з іншого салону, яку треба зняти, напишіть про це під час запису — оцінимо зняття індивідуально.",
   "ru":"Коррекцию делаем до трёх недель после аппликации — позже остаётся слишком мало своих ресниц, чтобы дополнить, и дешевле сделать комплект заново. Если у вас работа из другого салона, которую надо снять, напишите об этом при записи — оценим снятие индивидуально.",
   "en":"Fills are done within three weeks of the application — after that too few of your own lashes remain and a fresh full set works out cheaper. If you have work from another salon to take off, mention it when booking and we will quote the removal separately."},
 ],
 "faq": [
  {"q":{"pl":"Ile kosztuje przedłużanie rzęs w Szczecinie?",
        "uk":"Скільки коштує нарощування вій у Щеціні?",
        "ru":"Сколько стоит наращивание ресниц в Щецине?",
        "en":"How much do lash extensions cost in Szczecin?"},
   "a":{"pl":"Metoda 1:1 kosztuje {cena:Przedłużanie rzęs 1:1}, 1:2 — {cena:Przedłużanie rzęs 1:2}, 1:3 — {cena:Przedłużanie rzęs 1:3}, 4:1 — {cena:Przedłużanie rzęs 4:1}, a 5:1 — {cena:Przedłużanie rzęs 5:1}. Uzupełnienie do trzech tygodni to {cena:Uzupełnienie rzęs (do 3 tygodni)}. Ceny są takie same jak w Booksy.",
        "uk":"Метод 1:1 коштує {cena:Przedłużanie rzęs 1:1}, 1:2 — {cena:Przedłużanie rzęs 1:2}, 1:3 — {cena:Przedłużanie rzęs 1:3}, 4:1 — {cena:Przedłużanie rzęs 4:1}, 5:1 — {cena:Przedłużanie rzęs 5:1}. Корекція до трьох тижнів — {cena:Uzupełnienie rzęs (do 3 tygodni)}. Ціни ті самі, що в Booksy.",
        "ru":"Метод 1:1 стоит {cena:Przedłużanie rzęs 1:1}, 1:2 — {cena:Przedłużanie rzęs 1:2}, 1:3 — {cena:Przedłużanie rzęs 1:3}, 4:1 — {cena:Przedłużanie rzęs 4:1}, 5:1 — {cena:Przedłużanie rzęs 5:1}. Коррекция до трёх недель — {cena:Uzupełnienie rzęs (do 3 tygodni)}. Цены те же, что в Booksy.",
        "en":"The 1:1 method costs {cena:Przedłużanie rzęs 1:1}, 1:2 is {cena:Przedłużanie rzęs 1:2}, 1:3 is {cena:Przedłużanie rzęs 1:3}, 4:1 is {cena:Przedłużanie rzęs 4:1} and 5:1 is {cena:Przedłużanie rzęs 5:1}. A fill within three weeks is {cena:Uzupełnienie rzęs (do 3 tygodni)}. Prices match Booksy."}},
  {"q":{"pl":"Ile trzymają się przedłużone rzęsy?",
        "uk":"Скільки тримаються нарощені вії?",
        "ru":"Сколько держатся нарощенные ресницы?",
        "en":"How long do lash extensions last?"},
   "a":{"pl":"Około trzech, czterech tygodni, zależnie od cyklu wzrostu własnych rzęs. Wypadają razem z rzęsą, na której są przyklejone, więc ubytek jest stopniowy, a nie nagły.",
        "uk":"Близько трьох-чотирьох тижнів, залежно від циклу росту власних вій. Вони випадають разом із вією, на яку приклеєні, тож втрата поступова, а не раптова.",
        "ru":"Около трёх-четырёх недель, в зависимости от цикла роста собственных ресниц. Они выпадают вместе с ресницей, на которую приклеены, поэтому убыль постепенная, а не резкая.",
        "en":"About three to four weeks, depending on your natural lash growth cycle. They shed together with the lash they are attached to, so the loss is gradual rather than sudden."}},
  {"q":{"pl":"Czy przedłużanie rzęs niszczy własne rzęsy?",
        "uk":"Чи псує нарощування власні вії?",
        "ru":"Портит ли наращивание собственные ресницы?",
        "en":"Do extensions damage natural lashes?"},
   "a":{"pl":"Nie, jeśli objętość i długość są dobrane do grubości własnej rzęsy, a zdejmowanie robi się preparatem, nie na siłę. Problemy pojawiają się przy zbyt ciężkich objętościach i przy odrywaniu rzęs w domu.",
        "uk":"Ні, якщо об'єм і довжина підібрані під товщину власної вії, а зняття робиться ремувером, а не силою. Проблеми з'являються при надто важких об'ємах і при зриванні вій удома.",
        "ru":"Нет, если объём и длина подобраны под толщину собственной ресницы, а снятие делается ремувером, а не силой. Проблемы появляются при слишком тяжёлых объёмах и при срывании ресниц дома.",
        "en":"No, provided the volume and length suit the thickness of your own lash and removal is done with a remover rather than by force. Problems come from over-heavy volumes and from pulling lashes off at home."}},
  {"q":{"pl":"Jak dbać o rzęsy po zabiegu?",
        "uk":"Як доглядати за віями після процедури?",
        "ru":"Как ухаживать за ресницами после процедуры?",
        "en":"How do I care for lashes afterwards?"},
   "a":{"pl":"Pierwsze 24 godziny bez wody i pary, potem normalnie. Nie używaj tłustych demakijaży ani wodoodpornego tuszu, nie śpij twarzą w poduszce i nie podkręcaj rzęs zalotką.",
        "uk":"Перші 24 години без води та пари, далі як завжди. Не використовуйте жирні засоби для зняття макіяжу й водостійку туш, не спіть обличчям у подушку і не підкручуйте вії щипцями.",
        "ru":"Первые 24 часа без воды и пара, дальше как обычно. Не используйте жирные средства для снятия макияжа и водостойкую тушь, не спите лицом в подушку и не подкручивайте ресницы щипцами.",
        "en":"No water or steam for the first 24 hours, then as normal. Avoid oily make-up removers and waterproof mascara, do not sleep face-down and do not use lash curlers."}},
 ],
}

SEO["brwi"] = {
 "h": {"pl":"Brwi i laminacja rzęs w Szczecinie",
       "uk":"Брови та ламінування вій у Щеціні",
       "ru":"Брови и ламинирование ресниц в Щецине",
       "en":"Brows and lash lamination in Szczecin"},
 "text": [
  {"pl":"Laminacja brwi układa włoski w jednym kierunku i utrzymuje ten kształt przez cztery do sześciu tygodni. To zabieg dla osób, którym brwi rosną w różne strony albo mają prześwity — po ułożeniu łuk wygląda na gęstszy, bez rysowania kredką. Do laminacji dokładamy botoks, który odbudowuje włosek po zabiegu chemicznym.",
   "uk":"Ламінування брів укладає волоски в одному напрямку і тримає форму чотири-шість тижнів. Це процедура для тих, у кого брови ростуть у різні боки або є просвіти: після укладання дуга виглядає густішою, без олівця. До ламінування додаємо ботокс, який відновлює волосок після хімічної дії.",
   "ru":"Ламинирование бровей укладывает волоски в одном направлении и держит форму четыре-шесть недель. Это процедура для тех, у кого брови растут в разные стороны или есть просветы: после укладки дуга выглядит гуще, без карандаша. К ламинированию добавляем ботокс, который восстанавливает волосок после химического воздействия.",
   "en":"Brow lamination sets the hairs in one direction and holds that shape for four to six weeks. It suits people whose brows grow in different directions or have gaps — once set, the arch looks fuller without pencil. We add botox to the lamination to rebuild the hair after the chemical step."},
  {"pl":"Geometrię brwi wyznaczamy pod rysy twarzy, a nie pod jeden modny kształt. Regulujemy woskiem i pincetą, koloryzujemy henną pudrową — ta trzyma się na skórze kilka dni, a na włosku do trzech tygodni, więc łuk zostaje wypełniony także tam, gdzie włosów brakuje.",
   "uk":"Геометрію брів визначаємо під риси обличчя, а не під одну модну форму. Коригуємо воском і пінцетом, фарбуємо пудровою хною — вона тримається на шкірі кілька днів, а на волосині до трьох тижнів, тож дуга залишається заповненою й там, де волосків бракує.",
   "ru":"Геометрию бровей определяем под черты лица, а не под одну модную форму. Корректируем воском и пинцетом, красим пудровой хной — она держится на коже несколько дней, а на волоске до трёх недель, так что дуга остаётся заполненной и там, где волосков не хватает.",
   "en":"We set brow geometry to your features, not to one trending shape. We shape with wax and tweezers and tint with powder henna, which holds on the skin for a few days and on the hair for up to three weeks, so the arch stays filled even where hairs are missing."},
  {"pl":"Laminacja rzęs to alternatywa dla przedłużania: własne rzęsy zostają uniesione od nasady i podkręcone, bez doklejania czegokolwiek. Efekt trzyma się sześć do ośmiu tygodni i nie wymaga uzupełnień — dobre rozwiązanie, jeśli chcesz otwarte spojrzenie, ale nie chcesz wracać do salonu co trzy tygodnie.",
   "uk":"Ламінування вій — альтернатива нарощуванню: власні вії піднімають від основи й підкручують, нічого не приклеюючи. Ефект тримається шість-вісім тижнів і не потребує корекцій — добрий варіант, якщо хочете відкритий погляд, але не хочете повертатися в салон кожні три тижні.",
   "ru":"Ламинирование ресниц — альтернатива наращиванию: собственные ресницы поднимают от основания и подкручивают, ничего не приклеивая. Эффект держится шесть-восемь недель и не требует коррекций — хороший вариант, если хотите открытый взгляд, но не хотите возвращаться в салон каждые три недели.",
   "en":"Lash lamination is an alternative to extensions: your own lashes are lifted at the root and curled, with nothing glued on. The effect holds for six to eight weeks and needs no fills — a good option if you want an open look without returning every three weeks."},
 ],
 "faq": [
  {"q":{"pl":"Ile kosztuje laminacja brwi w Szczecinie?",
        "uk":"Скільки коштує ламінування брів у Щеціні?",
        "ru":"Сколько стоит ламинирование бровей в Щецине?",
        "en":"How much does brow lamination cost in Szczecin?"},
   "a":{"pl":"Laminacja brwi z botoksem kosztuje {cena:Laminacja brwi + botox}, a z koloryzacją {cena:Laminacja brwi + botox + koloryzacja}. Sama regulacja woskiem i pincetą to {cena:Regulacja brwi damska (wosk, pincet)}.",
        "uk":"Ламінування брів із ботоксом коштує 100 zł, з фарбуванням — 130 zł. Сама корекція воском і пінцетом — 50 zł, корекція з геометрією та фарбою — 100 zł.",
        "ru":"Ламинирование бровей с ботоксом стоит 100 zł, с окрашиванием — 130 zł. Сама коррекция воском и пинцетом — 50 zł, коррекция с геометрией и краской — 100 zł.",
        "en":"Brow lamination with botox is 100 zł, and with tinting 130 zł. Shaping alone with wax and tweezers is 50 zł, shaping with geometry and tint 100 zł."}},
  {"q":{"pl":"Jak długo trzyma się laminacja brwi?",
        "uk":"Скільки тримається ламінування брів?",
        "ru":"Сколько держится ламинирование бровей?",
        "en":"How long does brow lamination last?"},
   "a":{"pl":"Od czterech do sześciu tygodni. Powtarzać można nie częściej niż co miesiąc — częstsze zabiegi przesuszają włosek.",
        "uk":"Від чотирьох до шести тижнів. Повторювати можна не частіше ніж раз на місяць — частіші процедури пересушують волосок.",
        "ru":"От четырёх до шести недель. Повторять можно не чаще раза в месяц — более частые процедуры пересушивают волосок.",
        "en":"Four to six weeks. Do not repeat more often than monthly — more frequent treatments dry the hair out."}},
  {"q":{"pl":"Laminacja rzęs czy przedłużanie — co wybrać?",
        "uk":"Ламінування вій чи нарощування — що обрати?",
        "ru":"Ламинирование ресниц или наращивание — что выбрать?",
        "en":"Lash lamination or extensions?"},
   "a":{"pl":"Laminacja podkręca to, co masz, i wymaga mniej uwagi — nie ma uzupełnień, można używać tuszu. Przedłużanie daje długość i gęstość, których własne rzęsy nie mają, ale wraca się co trzy tygodnie. Przy rzadkich, krótkich rzęsach lepiej działa przedłużanie.",
        "uk":"Ламінування підкручує те, що є, і потребує менше уваги: немає корекцій, можна користуватися тушшю. Нарощування дає довжину й густоту, яких немає у власних вій, але повертатися треба кожні три тижні. За рідких коротких вій краще працює нарощування.",
        "ru":"Ламинирование подкручивает то, что есть, и требует меньше внимания: нет коррекций, можно пользоваться тушью. Наращивание даёт длину и густоту, которых нет у своих ресниц, но возвращаться нужно каждые три недели. При редких коротких ресницах лучше работает наращивание.",
        "en":"Lamination curls what you already have and needs less upkeep: no fills, and you can wear mascara. Extensions add length and density your own lashes do not have, but you return every three weeks. For sparse, short lashes, extensions work better."}},
  {"q":{"pl":"Czy henna pudrowa uczula?",
        "uk":"Чи викликає пудрова хна алергію?",
        "ru":"Вызывает ли пудровая хна аллергию?",
        "en":"Can powder henna cause a reaction?"},
   "a":{"pl":"Rzadko, ale przy pierwszej wizycie i skórze wrażliwej robimy próbę uczuleniową. Powiedz nam o alergiach i przyjmowanych lekach przed zabiegiem.",
        "uk":"Рідко, але за першого візиту та чутливої шкіри робимо алергопробу. Скажіть нам про алергії та ліки перед процедурою.",
        "ru":"Редко, но при первом визите и чувствительной коже делаем аллергопробу. Скажите нам об аллергиях и принимаемых лекарствах до процедуры.",
        "en":"Rarely, but on a first visit or with sensitive skin we run a patch test. Tell us about allergies and any medication before the treatment."}},
 ],
}

SEO["masaz"] = {
 "h": {"pl":"Masaż w Szczecinie — rodzaje i czas trwania",
       "uk":"Масаж у Щеціні — види та тривалість",
       "ru":"Массаж в Щецине — виды и длительность",
       "en":"Massage in Szczecin — types and duration"},
 "text": [
  {"pl":"Najczęściej zamawiany jest masaż pleców i karku — pół godziny do trzech kwadransów pracy na odcinku szyjnym i piersiowym, po których da się swobodniej odwrócić głowę. To zabieg dla osób pracujących przy biurku, kierowców i wszystkich, którym po całym dniu drętwieją barki. Masaż klasyczny całego ciała trwa półtorej godziny, relaksacyjny godzinę lub dwie.",
   "uk":"Найчастіше замовляють масаж спини та шиї — від пів години до трьох чвертей години роботи на шийному та грудному відділах, після чого голова повертається вільніше. Це процедура для тих, хто працює за столом, для водіїв і всіх, у кого під кінець дня німіють плечі. Класичний масаж усього тіла триває півтори години, релаксаційний — годину або дві.",
   "ru":"Чаще всего заказывают массаж спины и шеи — от получаса до трёх четвертей часа работы на шейном и грудном отделах, после которых голова поворачивается свободнее. Это процедура для тех, кто работает за столом, для водителей и всех, у кого к концу дня немеют плечи. Классический массаж всего тела длится полтора часа, релаксационный — час или два.",
   "en":"The most requested treatment is a back and neck massage — thirty to forty-five minutes on the neck and thoracic spine, after which turning your head is easier again. It suits desk workers, drivers and anyone whose shoulders go numb by the end of the day. A full-body classic massage takes an hour and a half, a relaxing one an hour or two."},
  {"pl":"Na twarz mamy Kobido — japoński masaż liftingujący twarzy, szyi i dekoltu, który pobudza krążenie i rozluźnia napięte mięśnie mimiczne — oraz wersję z masażem transbukalnym, czyli pracą od wewnątrz policzków. To zabieg na godzinę i kwadrans, po którym twarz wygląda na wypoczętą przez kilka dni. Krótsze pozycje to masaż rąk i masaż stóp po pół godziny.",
   "uk":"Для обличчя є Кобідо — японський ліфтинговий масаж обличчя, шиї та декольте, що стимулює кровообіг і розслабляє напружені мімічні м'язи, — а також версія з трансбукальним масажем, тобто роботою зсередини щік. Це процедура на годину з чвертю, після якої обличчя кілька днів виглядає відпочилим. Коротші позиції — масаж рук і масаж стоп по пів години.",
   "ru":"Для лица есть Кобидо — японский лифтинговый массаж лица, шеи и декольте, который стимулирует кровообращение и расслабляет напряжённые мимические мышцы, — а также версия с трансбуккальным массажем, то есть работой изнутри щёк. Это процедура на час с четвертью, после которой лицо несколько дней выглядит отдохнувшим. Более короткие позиции — массаж рук и массаж стоп по полчаса.",
   "en":"For the face we offer Kobido — a Japanese lifting massage of the face, neck and décolletage that boosts circulation and relaxes tense facial muscles — and a version with a transbuccal massage, working from inside the cheeks. It takes an hour and a quarter, and the face looks rested for several days afterwards. The shorter options are a hand massage and a foot massage, half an hour each."},
  {"pl":"Ceny różnią się dla kobiet i mężczyzn, bo różni się czas i nakład pracy przy większej powierzchni ciała — obie stawki są wypisane w cenniku wyżej. Przed pierwszym masażem pytamy o kontuzje, ciążę, żylaki i choroby przewlekłe; przy części z nich masaż wymaga zgody lekarza.",
   "uk":"Ціни різняться для жінок і чоловіків, бо різняться час і обсяг роботи на більшій площі тіла — обидві ставки виписані у прайсі вище. Перед першим масажем питаємо про травми, вагітність, варикоз і хронічні хвороби; за частини з них масаж потребує згоди лікаря.",
   "ru":"Цены различаются для женщин и мужчин, потому что различаются время и объём работы на большей площади тела — обе ставки выписаны в прайсе выше. Перед первым массажем спрашиваем о травмах, беременности, варикозе и хронических болезнях; при части из них массаж требует согласия врача.",
   "en":"Prices differ for women and men because the time and workload over a larger body area differ — both rates are listed above. Before a first massage we ask about injuries, pregnancy, varicose veins and chronic conditions; some of them require a doctor's clearance."},
 ],
 "faq": [
  {"q":{"pl":"Ile kosztuje masaż w Szczecinie?",
        "uk":"Скільки коштує масаж у Щеціні?",
        "ru":"Сколько стоит массаж в Щецине?",
        "en":"How much does a massage cost in Szczecin?"},
   "a":{"pl":"Masaż klasyczny pleców i karku to {cena:Masaż klasyczny pleców i karku} za 30 minut, relaksacyjny pleców i karku {cena:Masaż relaksacyjny pleców i karku}, masaż klasyczny całego ciała {cena:Masaż klasyczny całego ciała}, relaksacyjny całego ciała od {cena:Masaż relaksacyjny całego ciała}. Kobido kosztuje {cena:Kobido – japoński liftingujący masaż twarzy}, masaż rąk i stóp po {cena:Masaż stóp}.",
        "uk":"Класичний масаж спини та шиї — 50 zł за 30 хвилин, релаксаційний спини та шиї — 140 zł, класичний масаж усього тіла — 200 zł, релаксаційний усього тіла — від 180 zł. Кобідо коштує 150 zł, масаж рук і стоп — по 50 zł.",
        "ru":"Классический массаж спины и шеи — 50 zł за 30 минут, релаксационный спины и шеи — 140 zł, классический массаж всего тела — 200 zł, релаксационный всего тела — от 180 zł. Кобидо стоит 150 zł, массаж рук и стоп — по 50 zł.",
        "en":"A classic back and neck massage is 50 zł for 30 minutes, a relaxing back and neck massage 140 zł, a full-body classic massage 200 zł and a relaxing full-body massage from 180 zł. Kobido costs 150 zł, hand and foot massages 50 zł each."}},
  {"q":{"pl":"Jaki masaż na ból pleców od siedzenia przy komputerze?",
        "uk":"Який масаж при болю в спині від сидіння за комп'ютером?",
        "ru":"Какой массаж при боли в спине от сидения за компьютером?",
        "en":"Which massage helps back pain from desk work?"},
   "a":{"pl":"Masaż klasyczny pleców i karku, najlepiej w serii — pojedyncza wizyta przynosi ulgę na kilka dni, seria czterech, sześciu zabiegów działa dłużej. Przy przewlekłym bólu warto wcześniej wykluczyć przyczynę u lekarza.",
        "uk":"Класичний масаж спини та шиї, найкраще курсом — один візит дає полегшення на кілька днів, курс із чотирьох-шести процедур діє довше. За хронічного болю варто спершу виключити причину в лікаря.",
        "ru":"Классический массаж спины и шеи, лучше курсом — один визит даёт облегчение на несколько дней, курс из четырёх-шести процедур действует дольше. При хронической боли стоит сначала исключить причину у врача.",
        "en":"A classic back and neck massage, ideally as a course — a single visit brings relief for a few days, a course of four to six lasts longer. With chronic pain, rule out the cause with a doctor first."}},
  {"q":{"pl":"Czy masaż jest dla kobiet w ciąży?",
        "uk":"Чи можна масаж вагітним?",
        "ru":"Можно ли массаж беременным?",
        "en":"Is massage safe during pregnancy?"},
   "a":{"pl":"W pierwszym trymestrze nie wykonujemy masażu. Później tylko po konsultacji i w pozycji bocznej, z pominięciem brzucha i odcinka lędźwiowego. Powiedz o ciąży przy rezerwacji.",
        "uk":"У першому триместрі масаж не виконуємо. Пізніше — лише після консультації та в положенні на боці, оминаючи живіт і поперек. Скажіть про вагітність під час запису.",
        "ru":"В первом триместре массаж не выполняем. Позже — только после консультации и в положении на боку, минуя живот и поясницу. Скажите о беременности при записи.",
        "en":"We do not massage during the first trimester. Later, only after consultation and lying on your side, avoiding the abdomen and lower back. Mention the pregnancy when booking."}},
 ],
}

SEO["blizny"] = {
 "h": {"pl":"Redukcja blizn i rozstępów w Szczecinie — mikroneedling",
       "uk":"Редукція шрамів і розтяжок у Щеціні — мікронідлінг",
       "ru":"Редукция шрамов и растяжек в Щецине — микронидлинг",
       "en":"Scar and stretch mark reduction in Szczecin — microneedling"},
 "text": [
  {"pl":"Mikroneedling to nakłuwanie skóry cienkimi igłami na kontrolowaną głębokość. Uszkodzenie jest celowe i mikroskopijne: uruchamia odbudowę kolagenu, przez co blizna spłaszcza się i blednie, a rozstęp traci ostrą granicę. Efekt buduje się przez kilka tygodni po zabiegu, nie od razu.",
   "uk":"Мікронідлінг — це проколювання шкіри тонкими голками на контрольовану глибину. Пошкодження цілеспрямоване й мікроскопічне: воно запускає відновлення колагену, завдяки чому шрам сплощується і світлішає, а розтяжка втрачає різку межу. Ефект наростає протягом кількох тижнів після процедури, а не одразу.",
   "ru":"Микронидлинг — это прокалывание кожи тонкими иглами на контролируемую глубину. Повреждение целенаправленное и микроскопическое: оно запускает восстановление коллагена, за счёт чего шрам уплощается и светлеет, а растяжка теряет резкую границу. Эффект нарастает в течение нескольких недель после процедуры, а не сразу.",
   "en":"Microneedling punctures the skin with fine needles to a controlled depth. The damage is deliberate and microscopic: it triggers collagen rebuilding, so the scar flattens and fades and the stretch mark loses its sharp edge. The result builds over several weeks after the session, not immediately."},
  {"pl":"Konsultacja jest darmowa i zawsze poprzedza pierwszy zabieg. Oglądamy bliznę, pytamy o to, kiedy powstała i jak się goiła, i mówimy, ilu zabiegów realnie potrzeba — świeże blizny reagują szybciej niż kilkunastoletnie, a keloidy wymagają osobnego podejścia. Nie zaczynamy pracy bez tej rozmowy.",
   "uk":"Консультація безкоштовна і завжди передує першій процедурі. Оглядаємо шрам, питаємо, коли він виник і як загоювався, і кажемо, скільки процедур реально потрібно: свіжі шрами реагують швидше за десятилітні, а келоїди потребують окремого підходу. Без цієї розмови роботу не починаємо.",
   "ru":"Консультация бесплатная и всегда предшествует первой процедуре. Осматриваем шрам, спрашиваем, когда он возник и как заживал, и говорим, сколько процедур реально нужно: свежие шрамы реагируют быстрее многолетних, а келоиды требуют отдельного подхода. Без этого разговора работу не начинаем.",
   "en":"The consultation is free and always precedes the first session. We look at the scar, ask when it formed and how it healed, and tell you how many sessions are realistically needed — fresh scars respond faster than decade-old ones, and keloids need a different approach. We do not start without that conversation."},
  {"pl":"Osobno pracujemy z blizną po cesarskim cięciu, ze starymi bliznami pooperacyjnymi oraz z rozstępami na biuście, brzuchu, pośladkach i udach. Po zabiegu skóra jest zaczerwieniona przez jeden, dwa dni, więc warto zaplanować go poza dniem, w którym masz ważne wyjście.",
   "uk":"Окремо працюємо зі шрамом після кесаревого розтину, зі старими післяопераційними шрамами та з розтяжками на грудях, животі, сідницях і стегнах. Після процедури шкіра червона один-два дні, тож краще планувати її не напередодні важливого виходу.",
   "ru":"Отдельно работаем со шрамом после кесарева сечения, со старыми послеоперационными шрамами и с растяжками на груди, животе, ягодицах и бёдрах. После процедуры кожа красная один-два дня, поэтому лучше планировать её не накануне важного выхода.",
   "en":"We work separately with caesarean scars, old post-surgical scars and stretch marks on the bust, abdomen, buttocks and thighs. The skin stays red for a day or two afterwards, so avoid booking it right before an important occasion."},
 ],
 "faq": [
  {"q":{"pl":"Ile zabiegów potrzeba, żeby zredukować bliznę?",
        "uk":"Скільки процедур потрібно, щоб зменшити шрам?",
        "ru":"Сколько процедур нужно, чтобы уменьшить шрам?",
        "en":"How many sessions does scar reduction take?"},
   "a":{"pl":"Zwykle od trzech do sześciu, w odstępach czterech, sześciu tygodni. Dokładną liczbę podajemy na darmowej konsultacji, po obejrzeniu blizny — bez tego każda liczba byłaby zgadywaniem.",
        "uk":"Зазвичай від трьох до шести з інтервалом чотири-шість тижнів. Точну кількість називаємо на безкоштовній консультації після огляду шраму — без цього будь-яке число було б здогадкою.",
        "ru":"Обычно от трёх до шести с интервалом четыре-шесть недель. Точное количество называем на бесплатной консультации после осмотра шрама — без этого любое число было бы догадкой.",
        "en":"Usually three to six, four to six weeks apart. We give the exact number at the free consultation, after seeing the scar — any figure before that would be guesswork."}},
  {"q":{"pl":"Czy mikroneedling boli?",
        "uk":"Чи болючий мікронідлінг?",
        "ru":"Больно ли делать микронидлинг?",
        "en":"Does microneedling hurt?"},
   "a":{"pl":"Zabieg wykonujemy w znieczuleniu miejscowym w kremie, więc odczuwalna jest wibracja i ucisk, nie kłucie. Na cienkiej skórze i przy bliznach na kościach bywa mniej komfortowo.",
        "uk":"Процедуру виконуємо під місцевою анестезією в кремі, тож відчувається вібрація й тиск, а не проколи. На тонкій шкірі та над кістками буває менш комфортно.",
        "ru":"Процедуру выполняем под местной анестезией в креме, поэтому чувствуется вибрация и давление, а не проколы. На тонкой коже и над костями бывает менее комфортно.",
        "en":"We use a topical anaesthetic cream, so you feel vibration and pressure rather than pricking. Thin skin and scars over bone can be less comfortable."}},
  {"q":{"pl":"Kiedy można zacząć pracę z blizną po cesarskim cięciu?",
        "uk":"Коли можна починати роботу зі шрамом після кесаревого розтину?",
        "ru":"Когда можно начинать работу со шрамом после кесарева сечения?",
        "en":"When can work on a caesarean scar begin?"},
   "a":{"pl":"Nie wcześniej niż pół roku po porodzie i tylko przy w pełni zagojonej, niebolesnej bliźnie. Przy karmieniu piersią i przy powikłaniach gojenia prosimy o zgodę lekarza.",
        "uk":"Не раніше ніж через пів року після пологів і лише за повністю загоєного, безболісного шраму. За грудного вигодовування та ускладнень загоєння просимо згоду лікаря.",
        "ru":"Не раньше чем через полгода после родов и только при полностью зажившем, безболезненном шраме. При грудном вскармливании и осложнениях заживления просим согласие врача.",
        "en":"No earlier than six months after the birth, and only on a fully healed, painless scar. If you are breastfeeding or healing was complicated, we ask for a doctor's clearance."}},
  {"q":{"pl":"Czy konsultacja jest płatna?",
        "uk":"Чи платна консультація?",
        "ru":"Платная ли консультация?",
        "en":"Is the consultation paid?"},
   "a":{"pl":"Nie, konsultacja jest darmowa i trwa około pół godziny. Umawia się ją tak samo jak każdą inną wizytę, przez Booksy.",
        "uk":"Ні, консультація безкоштовна і триває близько пів години. Записатися на неї можна так само, як на будь-який візит, через Booksy.",
        "ru":"Нет, консультация бесплатная и длится около получаса. Записаться на неё можно так же, как на любой визит, через Booksy.",
        "en":"No, the consultation is free and takes about half an hour. Book it like any other appointment, through Booksy."}},
 ],
}

SEO["spa"] = {
 "h": {"pl":"SPA i parafina na dłonie w Szczecinie",
       "uk":"SPA та парафін для рук у Щеціні",
       "ru":"SPA и парафин для рук в Щецине",
       "en":"Hand SPA and paraffin in Szczecin"},
 "text": [
  {"pl":"Zabieg parafinowy to ciepły okład, który zatrzymuje wilgoć w skórze i rozgrzewa stawy dłoni. Zimą, kiedy skóra pęka od mrozu i suchego powietrza w biurach, jest to najprostszy sposób, żeby dłonie przestały szczypać po dniu, dwóch.",
   "uk":"Парафінова процедура — це теплий компрес, який утримує вологу в шкірі та прогріває суглоби кистей. Узимку, коли шкіра тріскається від морозу й сухого повітря в офісах, це найпростіший спосіб, щоб руки перестали щипати вже за день-два.",
   "ru":"Парафиновая процедура — это тёплый компресс, который удерживает влагу в коже и прогревает суставы кистей. Зимой, когда кожа трескается от мороза и сухого воздуха в офисах, это самый простой способ, чтобы руки перестали щипать уже через день-два.",
   "en":"A paraffin treatment is a warm wrap that seals moisture into the skin and warms the joints of the hand. In winter, when skin cracks from cold and dry office air, it is the simplest way to stop your hands stinging within a day or two."},
  {"pl":"SPA dla rąk łączy peeling, maskę i masaż — trwa pół godziny i dobrze łączy się z manicure podczas jednej wizyty. Ta sama procedura jest dostępna dla stóp, zwykle jako dodatek do pedicure przed latem.",
   "uk":"SPA для рук поєднує пілінг, маску та масаж — триває пів години й добре поєднується з манікюром за один візит. Та сама процедура доступна для стоп, зазвичай як доповнення до педикюру перед літом.",
   "ru":"SPA для рук объединяет пилинг, маску и массаж — длится полчаса и хорошо сочетается с маникюром за один визит. Та же процедура доступна для стоп, обычно как дополнение к педикюру перед летом.",
   "en":"A hand SPA combines a scrub, a mask and a massage — half an hour, and it pairs well with a manicure in the same visit. The same treatment is available for feet, usually added to a pedicure before summer."},
  {"pl":"Zabieg jest bezpieczny dla większości osób, ale przy świeżych skaleczeniach, wypryskach i zaburzeniach czucia parafiny nie stosujemy. Jeśli masz problemy z krążeniem, powiedz o tym przed zabiegiem.",
   "uk":"Процедура безпечна для більшості, але за свіжих порізів, висипань і порушень чутливості парафін не застосовуємо. Якщо маєте проблеми з кровообігом, скажіть про це перед процедурою.",
   "ru":"Процедура безопасна для большинства, но при свежих порезах, высыпаниях и нарушениях чувствительности парафин не применяем. Если есть проблемы с кровообращением, скажите об этом перед процедурой.",
   "en":"The treatment is safe for most people, but we do not use paraffin on fresh cuts, rashes or where sensation is impaired. Tell us beforehand if you have circulation problems."},
 ],
 "faq": [
  {"q":{"pl":"Ile kosztuje SPA dla dłoni w Szczecinie?",
        "uk":"Скільки коштує SPA для рук у Щеціні?",
        "ru":"Сколько стоит SPA для рук в Щецине?",
        "en":"How much does a hand SPA cost in Szczecin?"},
   "a":{"pl":"SPA dla rąk, zimowa parafina oraz SPA dla nóg kosztują po {cena:Spa dla rąk}. Zabieg trwa od 30 do 40 minut.",
        "uk":"SPA для рук, зимовий парафін і SPA для ніг коштують по 100 zł. Процедура триває 30-40 хвилин.",
        "ru":"SPA для рук, зимний парафин и SPA для ног стоят по 100 zł. Процедура длится 30-40 минут.",
        "en":"Hand SPA, winter paraffin and foot SPA are 100 zł each. The treatment takes 30 to 40 minutes."}},
  {"q":{"pl":"Czy SPA można połączyć z manicure?",
        "uk":"Чи можна поєднати SPA з манікюром?",
        "ru":"Можно ли совместить SPA с маникюром?",
        "en":"Can a SPA be combined with a manicure?"},
   "a":{"pl":"Tak i tak robi to większość osób. Zaznacz obie usługi przy rezerwacji, żebyśmy zarezerwowali dłuższy termin.",
        "uk":"Так, і саме так робить більшість. Позначте обидві послуги під час запису, щоб ми забронювали довший час.",
        "ru":"Да, и именно так делает большинство. Отметьте обе услуги при записи, чтобы мы забронировали больше времени.",
        "en":"Yes, and most people do. Select both services when booking so we reserve a longer slot."}},
 ],
}
